remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs" # This is only required for local testing, not sure how GitHub deals with it
color_scheme: "dark"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "NewOCR on GitHub":
    - "//github.com/RubbaBoy/NewOCR"
