remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs" # Uncomment for local development
color_scheme: "dark"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "NewOCR on GitHub":
    - "//github.com/MSPaintIDE/NewOCR"
