remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"

# Enable or disable the site search
search_enabled: true

title: "NewOCR Wiki"

# Aux links for the upper right navigation
aux_links:
  "NewOCR on GitHub":
    - "//github.com/MSPaintIDE/NewOCR"
